### ISSUE TITLE
Save for later

### ISSUE THREAD

**Issue by Natim** [mariustresor1/focus-risk#1]
**Todo**

- [ ] Store the record with a draft status
- [ ] Add a way to load from the dashboard.

**Strech**
- [ ] In the dashboard add a draft filter or directory to show only drafts or only non drafts?
- [ ] Don't display it to the admin dashboard.
